10 RANDOMIZE = TIMER
20 LET NUMERO = RND(1*100)
25 PRINT VAL(NUMERO)
30 PRINT "Tente adivinhar o número (0 a 100)."
40 INPUT "Seu palpite: "; TENTATIVA
45 PRINT TENTATIVA
50 IF VAL(TENTATIVA) = VAL(NUMERO) THEN PRINT "Parabéns, você acertou!"
55 IF VAL(TENTATIVA) = VAL(NUMERO) THEN GOTO 90  
60 IF VAL(TENTATIVA) < VAL(NUMERO) THEN PRINT "O número é MAIOR que " + TENTATIVA
70 IF VAL(TENTATIVA) > VAL(NUMERO) THEN PRINT "O número é MENOR que " + TENTATIVA
80 GOTO 40
90 END
